/** Would You Rather prompts. Mix of light, philosophical, absurd, and
 *  mildly spicy. Each prompt is two options separated by ` / `. Free
 *  pack: 60 prompts; premium drops add themed packs (couples, work,
 *  travel, R-rated). */

export const WYR_PROMPTS: [string, string][] = [
  ["Have fingers as long as legs", "Have legs as long as fingers"],
  ["Never be able to sit down", "Never be able to lie down"],
  ["Fight 100 duck-sized horses", "Fight 1 horse-sized duck"],
  ["Be able to read minds", "Be able to predict the future"],
  ["Always be 10 minutes late", "Always be 20 minutes early"],
  ["Live without music", "Live without the internet"],
  ["Be famous but broke", "Rich but anonymous"],
  ["Only eat sweet food forever", "Only eat savory food forever"],
  ["Speak every language but only in song", "Speak only one language fluently"],
  ["Have no eyebrows", "Have unibrow you can't shave"],
  ["Be invisible", "Be able to fly"],
  ["Know when you'll die", "Know how you'll die"],
  ["Never hear music again", "Never watch a movie again"],
  ["Be trapped in an elevator with your ex", "Your boss"],
  ["Sweat coffee", "Cry maple syrup"],
  ["Have a personal chef", "A personal driver"],
  ["Live in a world with no rules for 24 hours", "Live in a world where everyone knows your thoughts for 24 hours"],
  ["Have no sense of smell", "No sense of taste"],
  ["Always have to say what you're thinking", "Never speak again"],
  ["Have free fast food for life", "Free fine dining once a month"],
  ["Forget everyone you know", "Be forgotten by everyone you know"],
  ["Be the funniest person at every party", "The smartest"],
  ["Give up coffee", "Give up alcohol"],
  ["Have one wish granted today", "Three wishes granted in ten years"],
  ["Travel back to the past", "Travel to the future"],
  ["Have terrible short-term memory", "Terrible long-term memory"],
  ["Be stuck on a desert island alone", "With someone you hate"],
  ["Win $1M", "Your best friend wins $10M"],
  ["Always wear the same outfit", "Never wear the same outfit twice"],
  ["Never use social media again", "Only use social media, nothing else"],
  ["Have spiders for fingers", "Snakes for hair"],
  ["Have a rewind button for your life", "A pause button"],
  ["Lose all your money", "Lose all your photos"],
  ["Speak only in whispers", "Only in shouts"],
  ["Marry your first crush", "Date only strangers forever"],
  ["Be a mediocre person doing great things", "A great person doing mediocre things"],
  ["Live to 120 in declining health", "Live to 70 in perfect health"],
  ["Be fluent in every language", "Play every musical instrument"],
  ["Know every fact", "Know every secret"],
  ["Never use a phone again", "Never use a computer again"],
  ["Have your internet history published", "Your DMs published"],
  ["Be stuck on a 10-hour flight next to a crying baby", "A loud talker"],
  ["Find true love", "Find $10M"],
  ["Always have bad breath you can't fix", "Always be mildly sweaty"],
  ["Own a dragon", "Be a dragon"],
  ["Be a sidekick to a hero", "A hero's arch-nemesis"],
  ["Never need to sleep", "Never need to eat"],
  ["Be reincarnated as a cat", "A dog"],
  ["Lose an argument every single time", "Win every argument but nobody likes you"],
  ["Always be too hot", "Always be too cold"],
  ["Have free therapy for life", "A free lawyer for life"],
  ["Start every sentence with 'legally speaking'", "End every sentence with 'allegedly'"],
  ["Know the day you'll meet your soulmate", "Know what they'll look like"],
  ["Live in a treehouse", "In a submarine"],
  ["Have 10 best friends", "One ride-or-die"],
  ["Get caught doing something embarrassing every day", "Have one unforgettably embarrassing moment go viral"],
  ["Have every song stuck in your head for a full day", "Only know the chorus of every song"],
  ["Be a character in your favorite movie", "Watch your life be made into a movie"],
  ["Have every meal be your favorite meal", "Have every meal be a surprise"],
  ["Be 5 years younger for 5 years", "10 years older immediately but die at 100 healthy"],
];
