/** Never Have I Ever prompts. Mix of mild (safe for work nights
 *  with the team) and spicy (late-night with close friends). Premium
 *  drop will add explicit-content and themed packs (college, travel,
 *  relationships). MVP stays PG-13 across the board. */

export const NHIE_PROMPTS: string[] = [
  "Never have I ever fallen asleep in a meeting.",
  "Never have I ever lied on a resume.",
  "Never have I ever sent a text to the wrong person.",
  "Never have I ever cried watching a Pixar movie.",
  "Never have I ever been stopped by the police.",
  "Never have I ever eaten something that fell on the floor (5-second rule).",
  "Never have I ever sung karaoke sober.",
  "Never have I ever pretended to be sick to skip work.",
  "Never have I ever gone to a concert alone.",
  "Never have I ever accidentally liked an old post while stalking someone.",
  "Never have I ever eaten cereal for dinner.",
  "Never have I ever forgotten a close friend's birthday.",
  "Never have I ever broken a bone.",
  "Never have I ever been kicked out of a bar or club.",
  "Never have I ever gotten lost in a foreign country.",
  "Never have I ever regifted a present.",
  "Never have I ever been stood up on a date.",
  "Never have I ever stolen something (even candy as a kid).",
  "Never have I ever quit a job by not showing up.",
  "Never have I ever fallen in public.",
  "Never have I ever taken credit for someone else's work.",
  "Never have I ever snooped through someone's phone.",
  "Never have I ever been to a wedding of someone I met once.",
  "Never have I ever ghosted a friend.",
  "Never have I ever binged an entire show in one day.",
  "Never have I ever lied to my parents about where I was.",
  "Never have I ever had a crush on a friend's sibling.",
  "Never have I ever driven with an empty gas tank.",
  "Never have I ever fallen for a scam.",
  "Never have I ever been in a fistfight.",
  "Never have I ever taken a sick day to do something fun.",
  "Never have I ever used a fake name at Starbucks.",
  "Never have I ever cried at work.",
  "Never have I ever been to a strip club.",
  "Never have I ever cheated on a test.",
  "Never have I ever hidden from a coworker I didn't want to talk to.",
  "Never have I ever slept through an alarm and missed something important.",
  "Never have I ever gossipped about someone in the room.",
  "Never have I ever stayed friends with an ex.",
  "Never have I ever been the designated driver all night.",
  "Never have I ever faked laughing at a joke I didn't get.",
  "Never have I ever been ghosted.",
  "Never have I ever accidentally left the house without something important (phone, keys, wallet).",
  "Never have I ever broken a promise to a close friend.",
  "Never have I ever made fun of a friend behind their back.",
  "Never have I ever given someone a bad gift on purpose.",
  "Never have I ever had food poisoning in a public place.",
  "Never have I ever done karaoke sober.",
  "Never have I ever had a crush on a teacher.",
  "Never have I ever fallen asleep in a movie theater.",
];
