/** Bad Answers — fill-in-the-blank card game in the CAH lineage but
 *  with original content and a less-shocking, more awkward-truths
 *  register. Keep it edgy but not hate-based; target is dark comedy
 *  and absurdism, not cruelty.
 *
 *  PROMPTS are the black cards — fill-in-the-blank questions.
 *  Use "___" exactly where a response card should slot in.
 *  Prompts with no blank are treated as standalone questions
 *  (player's response is their answer). */

export interface PromptCard {
  text: string;
}

export interface ResponseCard {
  text: string;
}

export const PROMPTS: PromptCard[] = [
  { text: "What did the HR rep find in my desk drawer? ___" },
  { text: "My therapist says my real problem is ___." },
  { text: "The real reason I left my last job was ___." },
  { text: "I can't believe the wedding was ruined by ___." },
  { text: "The company retreat was fine until someone brought ___." },
  { text: "My LinkedIn headline should really be: \"___\"." },
  { text: "The thing I'd save from a house fire is ___." },
  { text: "I got fired for ___." },
  { text: "At my funeral, I want them to play ___." },
  { text: "The secret to a happy marriage is ___." },
  { text: "Growing up, I thought all adults had ___." },
  { text: "I lost my appetite when I saw ___." },
  { text: "The last thing I Googled was ___." },
  { text: "What's ruining my sleep? ___." },
  { text: "The real Santa brings ___." },
  { text: "Never trust a man who owns ___." },
  { text: "What's the hold music at hell? ___." },
  { text: "I knew it was love when she showed me ___." },
  { text: "My password is ___." },
  { text: "My side hustle is ___." },
  { text: "The worst birthday present I ever got was ___." },
  { text: "I accidentally sent my boss ___." },
  { text: "What did my parents find in my room? ___." },
  { text: "The toughest part of parenting is ___." },
  { text: "I cope with existential dread by ___." },
  { text: "My dating app bio just says: \"___\"." },
  { text: "What's hiding in my browser history? ___." },
  { text: "If I ran the country, I'd outlaw ___." },
  { text: "My spirit animal is ___." },
  { text: "The jury found me not guilty by reason of ___." },
  { text: "My wellness routine is just ___." },
  { text: "What's the next viral trend? ___." },
  { text: "The reason my Uber rating is 3.1 is ___." },
  { text: "At the family reunion, we don't talk about ___." },
  { text: "The sermon this Sunday is on ___." },
  { text: "My startup pitch: Uber, but for ___." },
  { text: "What makes me unhirable? ___." },
  { text: "Airport security pulled me aside because of ___." },
  { text: "Before I die, I need to ___." },
  { text: "The group chat is for sharing ___." },
];

export const RESPONSES: ResponseCard[] = [
  { text: "a crippling debt" },
  { text: "my third cousin" },
  { text: "unsolicited fatherly advice" },
  { text: "gas station sushi" },
  { text: "a fully-grown raccoon" },
  { text: "untreated seasonal depression" },
  { text: "seventeen open tabs" },
  { text: "a mid-tier cryptocurrency" },
  { text: "the ghost of my ex" },
  { text: "microwaved leftovers" },
  { text: "a man named Greg" },
  { text: "one loud, assertive burp" },
  { text: "eye contact with a toddler" },
  { text: "crying in a Target parking lot" },
  { text: "six shots of espresso" },
  { text: "unpaid emotional labor" },
  { text: "the complete works of Ayn Rand" },
  { text: "an aggressively mediocre man" },
  { text: "a slow, public panic attack" },
  { text: "my mother's disappointment" },
  { text: "a printable PDF" },
  { text: "aggressive small talk" },
  { text: "unseasoned chicken" },
  { text: "a Labrador named Dave" },
  { text: "bottomless mimosas" },
  { text: "an HOA violation" },
  { text: "a light dusting of regret" },
  { text: "the dark web" },
  { text: "a corporate team-building exercise" },
  { text: "dad jeans" },
  { text: "a LinkedIn thought leader" },
  { text: "free hotel shampoo" },
  { text: "my childhood bedroom" },
  { text: "an exorcism gone wrong" },
  { text: "a single plain bagel" },
  { text: "uninvited fireworks" },
  { text: "the sound of my own voice" },
  { text: "existential dread" },
  { text: "a chiropractor with a podcast" },
  { text: "warm hospital Jell-O" },
  { text: "a Zoom call I forgot about" },
  { text: "aggressively good posture" },
  { text: "a 38-page Terms of Service" },
  { text: "being perceived" },
  { text: "a tastefully lit garage" },
  { text: "someone else's toothbrush" },
  { text: "an apology that goes too far" },
  { text: "a suspiciously wet handshake" },
  { text: "the ball pit at Chuck E. Cheese" },
  { text: "a conspiracy I half-believe" },
  { text: "running, but only from something" },
  { text: "a stranger's Venmo history" },
  { text: "a single, perfect french fry" },
  { text: "three gas station hot dogs" },
  { text: "an aggressive open floor plan" },
  { text: "a marriage of convenience" },
  { text: "my unread emails" },
  { text: "homemade kombucha" },
  { text: "the DMV on a Friday" },
  { text: "my entire Amazon wishlist" },
  { text: "someone named Tyler" },
  { text: "a passive-aggressive sticky note" },
  { text: "the eldest daughter complex" },
  { text: "a mid-afternoon cry" },
  { text: "exactly one Pilates class" },
  { text: "a 400-page fantasy trilogy" },
  { text: "a hand-knit sock puppet" },
  { text: "expired coupons" },
  { text: "a slightly haunted mirror" },
  { text: "my father's approval" },
  { text: "a cursed antique lamp" },
  { text: "unlimited breadsticks" },
  { text: "the ashes of a prior relationship" },
  { text: "a gym membership I don't use" },
  { text: "a weaponized smile" },
  { text: "a crush on my dentist" },
  { text: "the moral high ground" },
  { text: "an aggressively fit grandmother" },
  { text: "a conspiracy involving birds" },
  { text: "the mayor's secret Twitter" },
  { text: "a motivational poster" },
  { text: "one very loud cat" },
  { text: "a dim, underlit basement" },
  { text: "a diary I never burned" },
  { text: "pumpkin spice everything" },
  { text: "a single AirPod" },
  { text: "the fourteenth Marvel movie" },
  { text: "a gentle, relentless ex" },
  { text: "a 2006 Honda Civic" },
  { text: "uninvited commentary" },
  { text: "a surprise tax audit" },
  { text: "my unfinished novel" },
  { text: "a wedding reading from Reddit" },
  { text: "accidentally liking a 2014 post" },
  { text: "a haunted ventriloquist dummy" },
  { text: "the smell of a new car" },
  { text: "a soft, relentless optimism" },
  { text: "a man in a kilt" },
  { text: "an Excel spreadsheet of regrets" },
  { text: "a slow, apologetic jog" },
  { text: "the friendship bracelet I still wear" },
  { text: "a surprisingly honest TED talk" },
];
