/** Memory Jar prompts — alternating between the two players, drawn
 *  from a deck of "tell me about a memory" prompts about the shared
 *  past. Mix of small / medium / weighty so the conversation has
 *  texture. No scoring; the value is the archive. */

export const PROMPTS: string[] = [
  "A meal we’ve eaten together that I keep thinking about.",
  "The first time I felt understood by you.",
  "A small thing you did that I’ll never forget.",
  "A trip we took that didn’t go the way we expected.",
  "A movie we watched that we still quote.",
  "A song that became ours without us deciding it would.",
  "A moment I caught you laughing and thought: yes, this one.",
  "Something we’ve disagreed about that I now think you were right about.",
  "A walk we took that I’d take again exactly the same way.",
  "A friend who knew about us before we admitted it ourselves.",
  "A photo of us I look at when I want to remember a feeling.",
  "A rough day you helped me through and didn’t make a thing of.",
  "A place we found together that I’d never been before.",
  "A meal we tried to cook together that almost didn’t work out.",
  "A phrase you say that I’ve started saying.",
  "A story you’ve told me about your childhood that I keep re-reading in my head.",
  "Something I learned about you slowly, not all at once.",
  "A morning that felt like a small holiday for no reason.",
  "A risk we took that paid off.",
  "A risk we took that didn’t — and what we kept anyway.",
  "An ordinary night I’d pick over most great ones.",
  "A way you’ve grown since we met that you might not have noticed.",
  "A way I’ve grown since we met that I’d credit to you.",
  "A pet, a houseplant, or a rented appliance we cared for together.",
  "A weather system that made us closer.",
  "A traffic jam that made us closer.",
  "A song you sang badly that made me love you more.",
  "A meal you’ve cooked twice that I keep asking for.",
  "A book or article we both read and disagreed about.",
  "A holiday we made up traditions for.",
  "Something boring we did together that wasn’t boring.",
  "An argument we had that I’m glad we had.",
  "A thing you bought that I made fun of and now use constantly.",
  "A friend of yours I was nervous about meeting and then loved.",
  "A friend of mine you were nervous about meeting and then loved.",
  "A future memory I want us to make.",
  "A first I want to have with you that we haven’t had yet.",
  "Something I want to be better at by next year, with you.",
  "A version of us five years from now that I’m looking forward to.",
];
